"""update template_for_payment model

Revision ID: 2479f75773ba
Revises: b23aa962ccd8
Create Date: 2023-03-27 14:11:24.602709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2479f75773ba'
down_revision = 'b23aa962ccd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_template_for_payment_id'), 'template_for_payment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_for_payment_id'), table_name='template_for_payment')
    # ### end Alembic commands ###
