"""fix type_name field in TransferType

Revision ID: 793588eb6317
Revises: 2479f75773ba
Create Date: 2023-04-17 22:11:21.442468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793588eb6317'
down_revision = '2479f75773ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
