"""update_tables

Revision ID: e163f21990c6
Revises: 2479f75773ba
Create Date: 2023-04-05 10:23:07.489699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e163f21990c6'
down_revision = '2479f75773ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('additional_parameteres', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('additional_parameteres', 'payee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_additional_parameteres_id'), 'additional_parameteres', ['id'], unique=False)
    op.alter_column('payee', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('payee', 'INN',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('payee', 'payee_card_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_payee_id'), 'payee', ['id'], unique=False)
    op.alter_column('transfer_order', 'transfer_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer_order', 'purpose',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transfer_order', 'payee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transfer_order', 'start_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_transfer_order_id'), 'transfer_order', ['id'], unique=False)
    op.alter_column('transfer_type', 'percent_commission',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('transfer_type', 'max_sum',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.create_index(op.f('ix_transfer_type_id'), 'transfer_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_type_id'), table_name='transfer_type')
    op.alter_column('transfer_type', 'max_sum',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('transfer_type', 'percent_commission',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_index(op.f('ix_transfer_order_id'), table_name='transfer_order')
    op.alter_column('transfer_order', 'start_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transfer_order', 'payee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transfer_order', 'purpose',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transfer_order', 'transfer_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_payee_id'), table_name='payee')
    op.alter_column('payee', 'payee_card_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('payee', 'INN',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('payee', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_additional_parameteres_id'), table_name='additional_parameteres')
    op.alter_column('additional_parameteres', 'payee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('additional_parameteres', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
